### ISSUE TITLE
Crash after creating world as soon as I land in new world

### ISSUE THREAD

**Issue by crunkazcanbe** [Funwayguy/InfiniteInvo#10]
I do have a mod pack custom with 405 mods installed , and thought I would try this mod , and since it crashed I thought maybe since I have so many mods installed I could help you find incompatible mods , but I think this crash is with battle gear two mod , and this mod .

Crash http://pastebin.com/3VT2ZUxR

Could you please make this work with battlegear2 ?

Thank you .

-Crunk

**Comment by Funwayguy** [comment]
I could try and add a compatibility option for this (which would disable the ability to enlarge the UI) however what I would suggest is to ask the author of battlegear to do something like the Tinkers mod and add a tab button for a sub screen.

**Comment by crunkazcanbe** [comment]
Thanx man I suggested this to him here 
https://github.com/Mine-and-blade-admin/Battlegear2/issues/155

I told him to come here and get together with you .

Thanx

**Comment by crunkazcanbe** [comment]
@Funwayguy
I told the people over Battlegear2 mod and my response from the was as such below .
https://github.com/Mine-and-blade-admin/Battlegear2/issues/155

**Comment by Funwayguy** [comment]
*groans heavily* A 'tab' is impossible?! That's just laziness (Especially when Tinkers can do that just fine with minimal code). Guess it's up to me to make workarounds for people who are too stubborn yet again.

**Comment by crunkazcanbe** [comment]
Sorry man if i am the only one complaining about this dont worry about it . :-)

**Comment by Funwayguy** [comment]
No it's not you and I knew it would have eventually become a problem, just not over something as preventable as this. I'm just tired of dealing with developers like that.

**Comment by elix-x** [comment]
I'm having the same issue, and i'm interested: why it crashes with Battlegear and doesn't with Galacticraft and Tinkers construct?
Actually, to fix that you can make separate tab with additional slots (like in TC or Galacticraft) and in that case it WILL be compatible with ALL mods (because in that case you don't "replace" vanilla inventory, you make a new one instead).

**Comment by Funwayguy** [comment]
I have already made a fix for this in the next update which is to use the chest compatibility system with the vanilla inventory which works out better than adding a tab. The reason Battlegear is crashing things is because it is also force replacing the vanilla inventory GUI and not making any checks if the current GUI is in fact it's own. Galacticraft and Tinkers use tabbed subscreens instead (Which BattleGear2 should be doing), leaving the vanilla GUI alone even if it has been replaced with a modded version like mine.

**Comment by GotoLink** [comment]
Apparently, you didn't understand what i meant.
The Battlegear mod already adds a separate tab button for custom slot management.
It doesn't replace the vanilla GUI. And if your mod does, the error is on your side.
It should be clear from this report that the crash is induced by Battlegear because you replaced the InventoryPlayer instance in EntityPlayer. Dual-wielding will simply not work in Battlegear if it isn't the mod replacing this (besides possible crashes in vanilla itself). I only assumed your mod adds a feature such that you would also need to replace this. That is design incompatibility, likely impossible to fix.

**Comment by Funwayguy** [comment]
...well now I feel bad for misunderstanding the whole situation. Anyway the Inventory object itself can't be removed because it governs the access to the extra slots even when accessing other inventories.

**Comment by crunkazcanbe** [comment]
So this can not be fixed is what yall are saying ? If not i understand . So its a toss up dual wielding or more invo space. To bad we caint have both .

**Comment by elix-x** [comment]
@Funwayguy @crunkazcanbe 
Actually it can be fixed... But it's very very very hard:
Instead of replacing vanilla inventory, you will have to patch it using ASM without creating any derivations, which is not the easiest thing in the world!

**Comment by Funwayguy** [comment]
Didn't LexManos remove support for that in 1.8 though?

**Comment by elix-x** [comment]
He couldn't: Forge is based on it itself: Events, new methods, by default are not in mc. All this is inserted by Forge, when mc starts.
Why in eclipse you see files containing events? When you gradlew setupDecompWorkspace, it compiles mc, patches it and then decompiles for src view!
