### ISSUE TITLE
Upgrade/Downgrade(?)/Add/Remove armour disappears

### ISSUE THREAD

**Issue by awilliamson** [Funwayguy/InfiniteInvo#31]
When upgrading from 1.0.24 -> 1.0.33 ( pre 82cc9a4605 ) when restarting the server and players joining, they would lose their MagicalCrops Zivicio armour set, all of it. It would not be in their inventory, it would be gone.

When removing 1.0.33 ( pre 82cc9a4605 ), the same occurred.
When adding 1.0.33 ( @82cc9a4605 ), the same occurred.

I believe this was not caused by a client bug, as the mechanics of the armour set were not present server-side ( such as flight, step assist, fall damage, etc ).

**Comment by Funwayguy** [comment]
Is it only applying to this specific armor set or all armors? Either way I do believe I did make a minor change on how armor is loaded sometime between 1.0.24 and 1.0.33. Removing InfiniteInvo completely would also delete the armors because of the index at which they are offset in memory to make space for the extended inventory.

**Comment by awilliamson** [comment]
Haven't been able to try any other sets of armour. The upgrading/downgrading part was partially due to us requiring fixes you published today. If you wish, next fix, we'll try to have alternative armour on? Some vanilla perhaps?

**Comment by Funwayguy** [comment]
Just posted a new update. Let me know if the armor gets deleted this time

**Comment by awilliamson** [comment]
We tried it with Vanilla armour from 1.0.24 -> 1.0.25. None of the vanilla armour disappeared. I believe this is fixed now, will reopen if otherwise.
