### ISSUE TITLE
Configurable Inventory Items

### ISSUE THREAD

**Issue by earthcrafterman** [Funwayguy/InfiniteInvo#7]
Perhaps there could be a config that would allow specific items to unlock new inventory slot temporarily when held or worn, permanently (or until you die) when used with a right click, or both.

Also, please make this work on chests also, maybe give chests configurable inventory space and then have upgrades you can craft it with/place in it.

**Comment by Funwayguy** [comment]
I don't have any plans on doing any of these.
Items would mess with the order in which InfiniteInvo calculates the unlock position for slots especially between the client and server sides.
Chests would never get support for variable size because the vanilla container, GUI and tile entity would all need to be replaced in one go and the complications get exponentially harder when double chest handling gets involved.
In the end it's just overkill for the mod really, especially considering you can already have over 10 million inventory slots and honestly I like the mod look and feel as it is and don't wish to make it any bigger than it needs to be.

**Comment by earthcrafterman** [comment]
Okay, no prob. Thanks for the mod though, it's really cool
